spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 198608
    url: jdbc:mysql://localhost:3306/spring_boot?characterEncoding=utf-8&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  prod
label:
  master
girl:
  name: 小丽
  age : 12
